# Generated by Django 3.2.8 on 2021-10-05 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPRTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='dataSolicitacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
